### ISSUE TITLE
Is there a reason for leaving out the semicolons in the code?

### ISSUE THREAD

**Issue by ericaxu** [maxogden/art-of-node#18]
Curious to know. Thanks!

**Comment by yadakhov** [comment]
Starting to learn Node this week.  I had to google to make sure if semicolon was required or not.

It really should be there just to be consistent with the node style guide.  We don't want to teach beginners bad habits.
https://github.com/felixge/node-style-guide#use-semicolons

**Comment by maxogden** [comment]
You should choose the style you like. Just like wearing clothes. One style
is not better than another. I personally prefer
https://github.com/feross/standard
