### ISSUE TITLE
CoolBear example throws a error in RequireBin

### ISSUE THREAD

**Issue by pli88** [maxogden/art-of-node#52]
Below error shows up:

Bundling error: 

Error: CORS request rejected: https://wzrd.in/multi

Am i doing anything wrong here?

**Comment by maxogden** [comment]
sorry the module server ran out of disk space last night, its fixed now

**Comment by giabos** [comment]
this issue reemerged. Can you check please ?

**Comment by JayCole** [comment]
Same issue, thanks for the help
