### ISSUE TITLE
RequireBin example error

### ISSUE THREAD

**Issue by Charlotteis** [maxogden/art-of-node#68]
Hey! Thanks so much for this guide.

The 'more complicated example' on RequireBin seems to have an error.
This: http://requirebin.com/?gist=6031068 results in 

```
Uncaught TypeError: Cannot read property 'content' of undefined bundle.js:2 
```

Not sure what the fix is I'm afraid, but I figured you'd like to know.
Thanks again :sparkles:

**Comment by maxogden** [comment]
nice catch, thanks. I had to update the code on requirebin, but it should be working now (new link is http://requirebin.com/?gist=679b58d4237eaca37173)

**Comment by Charlotteis** [comment]
Works great, thanks!
